### ISSUE TITLE
cw721 addition (not from Stargaze Launchpad link) seems to have issue

### ISSUE THREAD

**Issue by mikedotexe** [starryzone/starrybot-discord#119]
As reported in the bugs channel in Discord, it sounds like The Strange Clan and Levana have run into and issue with this contract:
`juno1uw3pxkga3dxhqs28rjgpgqkvcuedhmc7ezm2yxvvaey9yugfu3fq7ej2wv`

<img width="207" alt="Screen Shot 2022-11-07 at 4 40 40 PM" src="https://user-images.githubusercontent.com/1042667/200445782-34b3c793-bee5-484e-a0dd-d852f1b38745.png">

I attempted to follow the normal process, using the button above, and could reproduce it.

```
TypeError: Cannot read properties of undefined (reading 'getTokenDetails')
    at getTokenDetails (/Users/mikepurvis/ic/starrybot-discord/src/astrolabe/index.js:27:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.getConfig (/Users/mikepurvis/ic/starrybot-discord/src/commands/tokenAdd/createTokenRule.js:30:29)
    at async Object.execute (/Users/mikepurvis/ic/starrybot-discord/src/utils/commands.js:46:9)
    at async Wizard.execute (/Users/mikepurvis/ic/starrybot-discord/src/wizardware/wizard.js:76:14)
    at async Wizardware.continue (/Users/mikepurvis/ic/starrybot-discord/src/wizardware/index.js:56:7)
    at async Client.interactionCreate (/Users/mikepurvis/ic/starrybot-discord/src/handlers/interactionCreate.js:46:4)
TypeError: Cannot read properties of undefined (reading 'name')
    at getTokenDetails (/Users/mikepurvis/ic/starrybot-discord/src/astrolabe/index.js:38:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.getConfig (/Users/mikepurvis/ic/starrybot-discord/src/commands/tokenAdd/createTokenRule.js:30:29)
    at async Object.execute (/Users/mikepurvis/ic/starrybot-discord/src/utils/commands.js:46:9)
    at async Wizard.execute (/Users/mikepurvis/ic/starrybot-discord/src/wizardware/wizard.js:76:14)
    at async Wizardware.continue (/Users/mikepurvis/ic/starrybot-discord/src/wizardware/index.js:56:7)
    at async Client.interactionCreate (/Users/mikepurvis/ic/starrybot-discord/src/handlers/interactionCreate.js:46:4)
```

**Comment by mikedotexe** [comment]
Solved with https://github.com/starryzone/starrybot-discord/commit/fe36b4648d132aa50f654d22645795088496433c
